### PR TITLE
Don't default-construct elements in a vector

### PR DESCRIPTION
**Pull request by kiroma**
If you *really* want to manually reserve the right amount of space for a vector, you have to call reserve.

### CODE REVIEW

**Comment by Repertoi-e** [comment]
Why don't you do
```cpp
for(size_t i = 1; i < argc; i++) {
    std::string argument = argv[i];  
    if(Arguments[i] == "-i") {
            if(++i < argc) {
                InputFiles.emplace_back(argv[i]);
            } else ...
    else if ...
}
```
instead?
You can skip the whole vector thing.

**Comment by Jackojc** [comment]
Or the easiest option of all found by a quick duckduckgo search:

```cpp
#include <iostream>
#include <vector>

int main(int argc, char const *argv[]) {

    std::vector<std::string> arguments(argv + 1, argv + argc);

    for (const auto& x: arguments)
        std::cout << x << std::endl;

    return 0;
}
```

**Comment by Repertoi-e** [comment]
I mean there is no point in iterating over the arguments twice when you can do it just once when you need them. Less code. Less iterating.

**Comment by Repertoi-e** [comment]
On line 36-40 the vector is created by looping over `0..argc` and constructing each string in the vector, then later on line 51 it is looping over the vector `1..vector.size()`. What I'm saying is that it's redundant to even have a vector at all. Instead you could just construct the string from `argv[i]` in the second loop.

**Comment by kiroma** [comment]
Well, at one point @Jackojc mentioned that output should always be to terminal and not to a file, so let's just do that.

**Pull request closed without merging**
